name: color_mixer_web_component
description: Web component app for the color_mixer package.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  color_mixer:
    path: ../../packages/color_mixer
  flutter:
    sdk: flutter
  multi_view_app:
    path: ../../packages/multi_view_app
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: false
