name: flutter_multi_view_web_embedding

packages:
  - packages/**
  - apps/**

sdkPath: .fvm/flutter_sdk

command:
  bootstrap:
    environment:
      sdk: ">=3.6.0 <4.0.0"
      flutter: ">=3.6.0 <4.0.0"
    dev_dependencies:
      very_good_analysis: ^7.0.0
  clean:
    hooks:
      pre:
        run: melos run .clean

scripts:
  # Internal: deep clean via git
  .clean:
    private: true
    description: Deep clean-up
    run: >
      git clean
      -dfX
      MELOS_PACKAGE_PATH
    packageFilters: {}

  format:
    description: Format codebase
    run: >
      dart format .
  format.ci:
    description: Format codebase and check for formatting errors
    run: >
      dart format --set-exit-if-changed .

  analyze:
    description: Analyze codebase
    run: >
      dart analyze .
  analyze.ci:
    description: Analyze codebase and check for analysis errors
    run: >
      dart analyze --fatal-infos --fatal-warnings .
