name: color_mixer
description: >-
  An interactive Flutter widget for mixing RGB color channels through custom
  gradient sliders.
publish_to: none
version: 0.1.0+1

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: false
